from typing import Any, Dict, List, Literal, Optional, Union
from pydantic import BaseModel, Field


FocusAreaType = Literal["Technical", "Behavioral", "Mixed", "Case"]
DifficultyLevel = Literal["Junior", "Mid-Level", "Senior", "Staff"]
ReflectionDecisionType = Literal["probe_deeper", "next_topic", "increase_difficulty", "decrease_difficulty", "simplify", "finish"]


class CandidateProfile(BaseModel):
    """Candidate background profile for session initialization."""
    target_role: str = Field(..., description="Target job title")
    resume_summary: str = Field(..., description="Technical background summary")
    focus_area: FocusAreaType = Field(default="Mixed", description="Interview focus area")


class InterviewStrategy(BaseModel):
    """Interview strategy produced by Planner Agent."""
    key_topics: List[str] = Field(..., min_length=1, description="Selected interview topics")
    initial_difficulty: DifficultyLevel = Field(default="Mid-Level", description="Starting difficulty level")
    focus_summary: str = Field(..., description="Strategy plan summary")


class EvaluationResult(BaseModel):
    """Candidate response evaluation from Evaluator Agent."""
    score: int = Field(..., ge=1, le=10, description="Response score (1-10)")
    feedback: Union[str, Dict[str, Any]] = Field(..., description="Qualitative response feedback")
    strong_points: List[str] = Field(default_factory=list, description="Demonstrated candidate strengths")
    weak_points: List[str] = Field(default_factory=list, description="Identified areas for growth")


class ReflectionOutput(BaseModel):
    """Routing decision from Reflection Agent."""
    decision: ReflectionDecisionType = Field(..., description="Routing decision")
    reasoning: str = Field(..., description="Decision rationale")
    follow_up_goal: Optional[str] = Field(None, description="Probing objective")
    follow_up_type: Optional[str] = Field(default="deeper_tradeoffs", description="Probing style")


class FinalReport(BaseModel):
    """Executive coaching report generated by Coach Agent."""
    overall_score: float = Field(..., ge=1.0, le=10.0, description="Overall score out of 10")
    executive_summary: str = Field(..., description="Performance summary")
    strong_areas: List[str] = Field(default_factory=list, description="Key candidate strengths")
    weak_areas: List[str] = Field(default_factory=list, description="Key study areas")
    recommendation: str = Field(..., description="Hiring recommendation")
    markdown_report: str = Field(..., description="Markdown executive report")
